name = "DeFiBenchGPTUSD"
chain = "mainnet"
address = "0x573F1f9ce9c60BF3E7B755b5a81E905d2d3A0704"

[calibers.mainnet]
address = "0x1CB9AF0D4C5e788BFECf97e855e4D2F84Bc906E2"
swapper = "0xe403614F41554fC0f7A3dD581878D0024Dc978E9"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/Dfb/DeFiBenchGPTUSD/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.arbitrum]
address = "0x1CB9AF0D4C5e788BFECf97e855e4D2F84Bc906E2"
swapper = "0xe403614F41554fC0f7A3dD581878D0024Dc978E9"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/Dfb/DeFiBenchGPTUSD/arbitrum/rootfiles"

[calibers.arbitrum.accounting_token]
address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.base]
address = "0x1CB9AF0D4C5e788BFECf97e855e4D2F84Bc906E2"
swapper = "0xe403614F41554fC0f7A3dD581878D0024Dc978E9"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/Dfb/DeFiBenchGPTUSD/base/rootfiles"

[calibers.base.accounting_token]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
name = "USD Coin"
symbol = "USDC"
