name = "intMkSrRoyUSDC"
chain = "mainnet"
address = "0xFa097420f0e2C72456B361a1eD85172B9ccd8c38"

[calibers.mainnet]
address = "0x5476F4E23dAA093Ce6700e1026013c55F7AF9083"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-integrations/machines/intMkSrRoyUSDC/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.arbitrum]
address = "0x5476F4E23dAA093Ce6700e1026013c55F7AF9083"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-integrations/machines/intMkSrRoyUSDC/arbitrum/rootfiles"

[calibers.arbitrum.accounting_token]
address = "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.base]
address = "0x5476F4E23dAA093Ce6700e1026013c55F7AF9083"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-integrations/machines/intMkSrRoyUSDC/base/rootfiles"

[calibers.base.accounting_token]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
name = "USD Coin"
symbol = "USDC"
