# Test machine deployed on the test v1.3 infrastructure
# https://operator.makina.finance/dashboard/strategies/0x375AD80bae82D6f135030bBeb9F9999EC264bA4a

name = "tstUSDCv13RX"
chain = "mainnet"
address = "0x375AD80bae82D6f135030bBeb9F9999EC264bA4a"

[calibers.mainnet]
address = "0x6D3D30dD3E294160C6D13dd939D9AE2842b6326d"
swapper = "0xab2022E642D6D16EC2Eb2a0a38DC27A83C4Aa940"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/tstUSDCv13RX/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.base]
address = "0x6D3D30dD3E294160C6D13dd939D9AE2842b6326d"
swapper = "0xab2022E642D6D16EC2Eb2a0a38DC27A83C4Aa940"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/tstUSDCv13RX/base/rootfiles"

[calibers.base.accounting_token]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
name = "USD Coin"
symbol = "USDC"
